# Generated by Django 3.1 on 2021-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.IntegerField()),
                ('prefijo', models.CharField(max_length=6)),
                ('fecha_ini_pref', models.DateField()),
                ('vigencia_pref', models.IntegerField()),
                ('nro_ini_pref', models.IntegerField()),
                ('nro_fin_pref', models.IntegerField()),
                ('resolucion_pref', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescrip', models.TextField()),
                ('taskEnd', models.BooleanField(default=False)),
                ('taskFile', models.FileField(blank=True, null=True, upload_to='staticfiles/%Y/%m/%d/')),
                ('taskFechaCrea', models.DateField()),
            ],
        ),
    ]
