# Generated by Django 3.1 on 2021-02-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='taskResol',
            field=models.BooleanField(default=False),
        ),
    ]
